name: Docker

on:
  push:
    branches: [main]

jobs:
  PROD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo secrets
        run: |
          tee -a key.json <<EOF
          ${{secrets.FIREBASEKEY}}
          EOF

          tee -a .env <<EOF
          APPID=${{ secrets.APPID }}
          DEVID=${{secrets.DEVID}}
          TOKEN="${{ secrets.TOKEN }}"
          DEVTOKEN="${{secrets.DEVTOKEN}}"
          GITTOKEN="${{ secrets.GITTOKEN }}"
          REDDIT_CLIENTID="${{ secrets.REDDIT_CLIENTID }}"
          REDDIT_CLIENTSECRET="${{ secrets.REDDIT_CLIENTSECRET }}"
          REDDIT_USERAGENT="${{ secrets.REDDIT_USERAGENT }}"
          TENORKEY="${{ secrets.TENORKEY }}"
          EOF

      - name: Build & Push Image
        run: |
          echo "${{secrets.DOCKERPW}}" | docker login -u "chinouvm" --password-stdin
          docker image build -t chinouvm/esie-bot:latest .
          docker push chinouvm/esie-bot:latest
