name: Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo secrets
        run: |
          echo APPID=${{ secrets.APPID }} > usr/src/bot/.env
          echo DEVID=${{ secrets.DEVID }} > usr/src/bot/.env
          echo TOKEN="${{ secrets.TOKEN }}" > usr/src/bot/.env
          echo DEVTOKEN="${{ secrets.DEVTOKEN }}" > usr/src/bot/.env
          echo GITTOKEN="${{ secrets.GITTOKEN }}" > usr/src/bot/.env
          echo REDDIT_CLIENTID="${{ secrets.REDDIT_CLIENTID }}" > usr/src/bot/.env
          echo REDDIT_CLIENTSECRET="${{ secrets.REDDIT_CLIENTSECRET }}" > usr/src/bot/.env
          echo REDDIT_USERAGENT="${{ secrets.REDDIT_USERAGENT }}" > usr/src/bot/.env
          echo TENORKEY="${{ secrets.TENORKEY }}" > usr/src/bot/.env
          echo -e '${{secrets.FIREBASEKEY}}' >> usr/src/bot/key.json

      - name: Build & Push Image
        run: |
          echo "${{secrets.DOCKERPW}}" | docker login -u "chinouvm" --password-stdin
          docker image build -t chinouvm/esiebot:latest .
          docker push chinouvm/esiebot:latest
