name: Esie Bot

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build & Push Docker Image
        run: |
          echo "${{secrets.DOCKERPW}}" | docker login -u "chinouvm" --password-stdin
          docker image build -t chinouvm/esiebot:v1 .
          docker push chinouvm/esiebot:v1
