name: Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo secrets
        run: |
          pwd
          echo APPID=${{ secrets.APPID }} > .env
          echo DEVID=${{ secrets.DEVID }} > .env
          echo TOKEN="${{ secrets.TOKEN }}" > .env
          echo DEVTOKEN="${{ secrets.DEVTOKEN }}" > .env
          echo GITTOKEN="${{ secrets.GITTOKEN }}" > .env
          echo REDDIT_CLIENTID="${{ secrets.REDDIT_CLIENTID }}" > .env
          echo REDDIT_CLIENTSECRET="${{ secrets.REDDIT_CLIENTSECRET }}" > .env
          echo REDDIT_USERAGENT="${{ secrets.REDDIT_USERAGENT }}" > .env
          echo TENORKEY="${{ secrets.TENORKEY }}" > .env
          echo -e '${{secrets.FIREBASEKEY}}' >> key.json
          ls -a
          cat .env

      - name: Build & Push Image
        run: |
          echo "${{secrets.DOCKERPW}}" | docker login -u "chinouvm" --password-stdin
          docker image build -t chinouvm/esie-bot:latest .
          docker push chinouvm/esie-bot:latest
